volumes:
  chat_nexlyhub_local_postgres_data: {}
  chat_nexlyhub_local_postgres_data_backups: {}
  node_modules: {}



services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: chat_nexlyhub_local_django
    container_name: chat_nexlyhub_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: chat_nexlyhub_production_postgres
    container_name: chat_nexlyhub_local_postgres
    volumes:
      - chat_nexlyhub_local_postgres_data:/var/lib/postgresql/data
      - chat_nexlyhub_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  vuejs:
    build:
      context: .
      dockerfile: ./compose/local/vuejs/Dockerfile
    image: chat_nexlyhub_local_vuejs
    container_name: chat_nexlyhub_local_vuejs
    ports:
      - "5173:5173"
    volumes:
      - ./chat-frontend:/app
      - node_modules:/app/node_modules

