services:
  docs:
    image: chat_nexlyhub_local_docs
    container_name: chat_nexlyhub_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./chat_nexlyhub:/app/chat_nexlyhub:z
    ports:
      - '9000:9000'
    command: /start-docs
