#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput
python manage.py migrate
exec /usr/local/bin/daphne -b 0.0.0.0 -p 5000 config.asgi:application  
