log:
  level: INFO

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    address: ':443'

certificatesResolvers:
  letsencrypt:
    acme:
      email: 'suraj-patidar@chat.nexlyhub.in'
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

http:
  routers:
    web-secure-router:
      rule: 'Host(`api-chat.nexlyhub.in`)'
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django
      tls:
        certResolver: letsencrypt

    web-media-router:
      rule: 'Host(`api-chat.nexlyhub.in`) && PathPrefix(`/media/`)'
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django-media
      tls:
        certResolver: letsencrypt

    web-frontend-router:
      rule: 'Host(`chat.nexlyhub.in`)'
      entryPoints:
        - web-secure
      service: nginx-frontend  # ✅ Change service from `vue-frontend` to `nginx`
      tls:
        certResolver: letsencrypt

  middlewares:
    csrf:
      headers:
        hostsProxyHeaders: ['X-CSRFToken']

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    django-media:
      loadBalancer:
        servers:
          - url: http://nginx:80

    nginx-frontend:  # ✅ Serve Vue.js from Nginx instead of Vue container
      loadBalancer:
        servers:
          - url: http://nginx:80

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
